trigger:
- master

pool:
  name: 'Hosted Windows Container'

variables:
  System.Debug: true

steps:
- task: PowerShell@2
  displayName: 'Install Required PowerShell Modules'
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)\install-modules.ps1'
    arguments: '"az"'
    errorActionPreference: 'stop'
    failOnStderr: false
    ignoreLASTEXITCODE: false
    pwsh: false
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  displayName: 'Exclude Unscannable ARM Templates'
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)\scripts\set-azsk-template-exclusions.ps1'
    arguments: '-AsCsv'
    errorActionPreference: 'stop'
    failOnStderr: false
    ignoreLASTEXITCODE: false
    pwsh: false

- task: AzSKARMTemplateChecker@1
  displayName: 'Run AzSK ARM Template Checker'
  inputs:
    armTemplateFilePath: '$(System.DefaultWorkingDirectory)\templates'
    skipControlsFromFile: '$(System.DefaultWorkingDirectory)\azsk-control-exceptions.csv'
    excludeFiles: '$(ExclusionTemplates)'
    disableAutoUpdate: false

- task: PowerShell@2
  displayName: 'Version ARM Templates'
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)\scripts\version-templates.ps1'
    errorActionPreference: 'stop'
    failOnStderr: false
    ignoreLASTEXITCODE: false
    pwsh: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Templates'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\templates' 
    artifactName: 'templates' 
    publishLocation: 'Container'
    parallel: false

- task: CopyFiles@2
  displayName: 'Copy Example Deployment Templates to Staging Directory'
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)\examples'
    contents: '**\*' 
    targetFolder: '$(Build.ArtifactStagingDirectory)\examples'
    cleanTargetFolder: true 
    overWrite: true
    flattenFolders: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Example Deployment Templates'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\examples' 
    artifactName: 'examples' 
    publishLocation: 'Container'
    parallel: false
